### ISSUE TITLE
Migrating to gap-packages

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/fr#11]
We have created new VO at https://github.com/gap-packages and suggest that all GAP packages could eventually migrate there - please consider doing so when it may be appropriate and less disruptive for your package.

**Comment by alex-konovalov** [comment]
The repository has been migrated, but all meta-information in the package still has to be updated to point to new URLs.

**Comment by fingolfin** [comment]
@laurentbartholdi Because of this, GAP 4.8.2 still ships fr 2.2.1 instead of 2.3.0.

**Comment by alex-konovalov** [comment]
Even more: our [register of PackageInfo.g URLs](https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/PackageUpdate/currentPackageInfoURLList) still points to http://laurentbartholdi.github.io/fr/PackageInfo.g. I can point it to http://gap-packages.github.io/fr/PackageInfo.g but of course this will have no effect prior to the new version of FR with corrected meta-information.
