### ISSUE TITLE
Cannot build fr-2.3.6

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/fr#16]
Running configure gives this error:
```
~/Projekte/GAP/pkg-distro/fr-2.3.6 $ ./configure
configure: error: cannot find sources (fr) in . or ..
```

**Comment by laurentbartholdi** [comment]
I just pulled the latest fr-2.3.6 from gap-packages.github.io/fr and unpacked it in ..../gap/pkg/fr-2.3.6.

I don't do anything special in the configure script, either; I use the standard AC_FIND_GAP command and look for a few programs like dot and display.

**Comment by fingolfin** [comment]
This is `fr-2.3.6` as shipped with GAP. I just verified, there are no diffs to the fr-2.3.6 available on the fr homepage.

You say that you pulled the package, but you don't go on to say whether running `./configure` in it worked for you. Does it?

While you are using `AC_FIND_GAP`, you are doing unusual things with autoconf: E.g. you have put `configure.ac` into a `cnf` subdirectory... So how do you (re)generate `configure`? I also see an highly unusual `AC_PREFIX_DEFAULT([${PWD}])` in it.

And most importantly, there is no `AC_CONFIG_SRCDIR` statement in it. I thought this gave an error when running autoconf, but apparently not? It seems to have default to the equivalent of `AC_CONFIG_SRCDIR([fr])`, and, well, it does not find a file namd `fr`, hence errors out.

**Comment by fingolfin** [comment]
Note: the error will not appear if the directory containing `fr` is named `fr`, because then the configure check for a file named `fr` in `.` or `..` succeeds. So this is why it might seem to work if you run it from a git clone, which is usually named `fr`. But if the dir is named `fr-2.3.6`, and thre is no other dir named `fr` in `..`, the error will appear.

**Comment by fingolfin** [comment]
So one way to fix it should be to insert this into your `configure.ac`:
```
AC_CONFIG_SRCDIR([PackageInfo.g])
```

This leaves the questions why you are using a configure script at all? It seems this is only done to locate a few binaries in the PATH. That could also be done during run time by GAP code (just an idea -- it would make it slightly easier for users to install you package, and avoid the hassle of maintaining a configure script just for that...

**Comment by fingolfin** [comment]
For example:
```
FindInPATH := function(name, extraPaths)
  local dirs;
  if IsBound(GAPInfo.SystemEnvironment.PATH) then
    dirs := SplitString(GAPInfo.SystemEnvironment.PATH,":");
  else
    dirs := [];
  fi;
  Append(dirs, extraPaths);
  dirs := List(paths,Directory);
  return Filename(dirs, name);
end;
```
And then:
```
gap> FindInPATH("dot",["/usr/local/graphviz/bin"]);
"/sw/bin/dot"
gap> FindInPATH("xyz",["/usr/local/graphviz/bin"]);
fail
```

**Comment by laurentbartholdi** [comment]
Thanks for the suggestion! I removed all the configuration stuff (which was a leftover from when FR and IMG were bundled).
